spring.application.name=productor-alertas

server.port=8081

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

app.rabbitmq.cola-alertas-oracle=cola.alertas.oracle
app.rabbitmq.cola-alertas-json=cola.alertas.json